#!/usr/bin/env zsh


RED="\e[33m"
GREEN="\e[32m"
BOLD="\e[1m"
ENDCOLOR="\e[0m"

echo -e "${RED}This is some red text, ${ENDCOLOR}"
echo -e "${GREEN}And this is some green text${ENDCOLOR}"

clear
echo -e "${RED}>${ENDCOLOR} activities"
echo -e "${RED}>${ENDCOLOR} standard_library"
echo -e "${RED}>${ENDCOLOR} statistics"
sleep 1

clear
echo -e "${RED}>${ENDCOLOR} activities"
echo -e "${RED}${ENDCOLOR} standard_library"
echo -e "  ${RED}□${ENDCOLOR} number_of_downloads"
echo -e "  ${RED}□${ENDCOLOR} number_of_packages"
echo -e "  ${RED}>${ENDCOLOR} package"
echo -e "  ${RED}>${ENDCOLOR} packages"
echo -e "${RED}>${ENDCOLOR} statistics"
sleep 1

clear
echo -e "${RED}>${ENDCOLOR} activities"
echo -e "${RED}${ENDCOLOR} standard_library"
echo -e "  ${RED}□${ENDCOLOR} number_of_downloads"
echo -e "  ${RED}□${ENDCOLOR} number_of_packages"
echo -e "  ${RED}${ENDCOLOR} package"
echo -e "    ${RED}■${ENDCOLOR} name*: ${GREEN}\"\"${ENDCOLOR}"
echo -e "    ${RED}□${ENDCOLOR} builds"
echo -e "    ${RED}□${ENDCOLOR} coverage"
echo -e "    ${RED}>${ENDCOLOR} latest_release"
echo -e "    ${RED}□${ENDCOLOR} name"
echo -e "    ️${RED}□${ENDCOLOR} number_of_downloads"
echo -e "  ${RED}>${ENDCOLOR} packages"
echo -e "${RED}>${ENDCOLOR} statistics"
sleep 1

clear
echo -e "${RED}>${ENDCOLOR} activities"
echo -e "${RED}${ENDCOLOR} standard_library"
echo -e "  ${RED}□${ENDCOLOR} number_of_downloads"
echo -e "  ${RED}□${ENDCOLOR} number_of_packages"
echo -e "  ${RED}${ENDCOLOR} package"
echo -e "    ${RED}■${ENDCOLOR} name*: ${GREEN}\"argpa\"${ENDCOLOR}"
echo -e "    ${RED}□${ENDCOLOR} builds"
echo -e "    ${RED}□${ENDCOLOR} coverage"
echo -e "    ${RED}>${ENDCOLOR} latest_release"
echo -e "    ${RED}□${ENDCOLOR} name"
echo -e "    ️${RED}□${ENDCOLOR} number_of_downloads"
echo -e "  ${RED}>${ENDCOLOR} packages"
echo -e "${RED}>${ENDCOLOR} statistics"
sleep 1

clear
echo -e "${RED}>${ENDCOLOR} activities"
echo -e "${RED}${ENDCOLOR} standard_library"
echo -e "  ${RED}□${ENDCOLOR} number_of_downloads"
echo -e "  ${RED}□${ENDCOLOR} number_of_packages"
echo -e "  ${RED}${ENDCOLOR} package"
echo -e "    ${RED}■${ENDCOLOR} name*: ${GREEN}\"argparse\"${ENDCOLOR}"
echo -e "    ${RED}□${ENDCOLOR} builds"
echo -e "    ${RED}□${ENDCOLOR} coverage"
echo -e "    ${RED}>${ENDCOLOR} latest_release"
echo -e "    ${RED}□${ENDCOLOR} name"
echo -e "    ️${RED}□${ENDCOLOR} number_of_downloads"
echo -e "  ${RED}>${ENDCOLOR} packages"
echo -e "${RED}>${ENDCOLOR} statistics"
sleep 1

clear
echo -e "${RED}>${ENDCOLOR} activities"
echo -e "${RED}${ENDCOLOR} standard_library"
echo -e "  ${RED}□${ENDCOLOR} number_of_downloads"
echo -e "  ${RED}□${ENDCOLOR} number_of_packages"
echo -e "  ${RED}${ENDCOLOR} package"
echo -e "    ${RED}■${ENDCOLOR} name*: ${GREEN}\"argparse\"${ENDCOLOR}"
echo -e "    ${RED}□${ENDCOLOR} builds"
echo -e "    ${RED}□${ENDCOLOR} coverage"
echo -e "    ${RED}>${ENDCOLOR} latest_release"
echo -e "    ${RED}■${ENDCOLOR} name"
echo -e "    ️${RED}□${ENDCOLOR} number_of_downloads"
echo -e "  ${RED}>${ENDCOLOR} packages"
echo -e "${RED}>${ENDCOLOR} statistics"
sleep 1

clear
echo -e "${RED}>${ENDCOLOR} activities"
echo -e "${RED}${ENDCOLOR} standard_library"
echo -e "  ${RED}□${ENDCOLOR} number_of_downloads"
echo -e "  ${RED}□${ENDCOLOR} number_of_packages"
echo -e "  ${RED}${ENDCOLOR} package"
echo -e "    ${RED}■${ENDCOLOR} name*: ${GREEN}\"argparse\"${ENDCOLOR}"
echo -e "    ${RED}□${ENDCOLOR} builds"
echo -e "    ${RED}□${ENDCOLOR} coverage"
echo -e "    ${RED}${ENDCOLOR} latest_release"
echo -e "      ${RED}□${ENDCOLOR} description"
echo -e "      ${RED}□${ENDCOLOR} version"
echo -e "    ${RED}■${ENDCOLOR} name"
echo -e "    ️${RED}□${ENDCOLOR} number_of_downloads"
echo -e "  ${RED}>${ENDCOLOR} packages"
echo -e "${RED}>${ENDCOLOR} statistics"
sleep 1

clear
echo -e "${RED}>${ENDCOLOR} activities"
echo -e "${RED}${ENDCOLOR} standard_library"
echo -e "  ${RED}□${ENDCOLOR} number_of_downloads"
echo -e "  ${RED}□${ENDCOLOR} number_of_packages"
echo -e "  ${RED}${ENDCOLOR} package"
echo -e "    ${RED}■${ENDCOLOR} name*: ${GREEN}\"argparse\"${ENDCOLOR}"
echo -e "    ${RED}□${ENDCOLOR} builds"
echo -e "    ${RED}□${ENDCOLOR} coverage"
echo -e "    ${RED}${ENDCOLOR} latest_release"
echo -e "      ${RED}□${ENDCOLOR} description"
echo -e "      ${RED}■${ENDCOLOR} version"
echo -e "    ${RED}■${ENDCOLOR} name"
echo -e "    ️${RED}□${ENDCOLOR} number_of_downloads"
echo -e "  ${RED}>${ENDCOLOR} packages"
echo -e "${RED}>${ENDCOLOR} statistics"
sleep 2

clear
cat <<EOF | jq
{
  "data": {
    "standard_library": {
      "package": {
        "name": "argparse",
        "latest_release": {
          "version": "0.1.0"
        }
      }
    }
  }
}
EOF
